services:
    twig.environment:
        class: Twig_Environment
        arguments: [@twig.loader]

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: ['src/KpiReport/Resources/templates']
